FROM python:3.11-slim

WORKDIR /simulator

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY simulate_mqtt.py .

CMD ["python", "simulate_mqtt.py"]